var WA="919654638990",D=[["Devil in Pinstripes", "Ravi Subramanian", "Fiction", "images/book-01.webp", "fiction thriller business", 0], ["The Incredible Banker", "Ravi Subramanian", "Fiction", "images/book-02.webp", "fiction thriller business", 0], ["The 7 Habits of Highly Effective People", "Stephen R. Covey", "Self-Help", "images/book-03.webp", "focus habits growth inspire", 0], ["The Subtle Art of Not Giving a F*ck", "Mark Manson", "Self-Help", "images/book-04.webp", "calm mind growth inspire", 0], ["Leaders Eat Last", "Simon Sinek", "Business", "images/book-05.webp", "business", 0], ["Sapiens: A Brief History of Humankind", "Yuval Noah Harari", "Ideas", "images/book-06.webp", "history mind", 0], ["Hannibal: Enemy of Rome", "Ben Kane", "Fiction", "images/book-07.webp", "fiction history", 0], ["The Book of Clarity", "Paras Chopra", "Business", "images/book-08.webp", "business mind", 0], ["Ask and It Is Given", "Esther & Jerry Hicks", "Self-Help", "images/book-09.webp", "inspire calm growth", 0], ["Deep Thinking", "Garry Kasparov", "Ideas", "images/book-10.webp", "mind", 0], ["21 Lessons for the 21st Century", "Yuval Noah Harari", "Ideas", "images/book-11.webp", "history mind", 0], ["Fooled by Randomness", "Nassim Nicholas Taleb", "Business", "images/book-12.webp", "business money mind", 0], ["The Hunger Games", "Suzanne Collins", "Fiction", "images/book-13.webp", "fiction", 0], ["The Art of Being Alone", "Renuka Gavrani", "Self-Help", "images/book-14.webp", "calm inspire growth", 1], ["Wings of Fire", "A.P.J. Abdul Kalam", "Biography", "images/book-15.webp", "bio india inspire", 1], ["A Promised Land", "Barack Obama", "Biography", "images/book-16.webp", "bio history", 1], ["An Autobiography: My Experiments with Truth", "M.K. Gandhi", "Biography", "images/book-17.webp", "bio india history inspire", 1], ["The Alchemist", "Paulo Coelho", "Fiction", "images/book-18.webp", "fiction inspire", 1], ["Dopamine Detox", "Thibaut Meurisse", "Self-Help", "images/book-19.webp", "focus habits calm growth", 1], ["Thinking, Fast and Slow", "Daniel Kahneman", "Ideas", "images/book-20.webp", "mind money", 1], ["Atomic Habits", "James Clear", "Self-Help", "images/book-21.webp", "habits focus growth", 1], ["The Art of Thinking Clearly", "Rolf Dobelli", "Ideas", "images/book-22.webp", "mind", 1], ["Deep Work", "Cal Newport", "Self-Help", "images/book-23.webp", "focus growth", 1], ["King of Envy", "Ana Huang", "Fiction", "images/book-24.webp", "fiction romance", 1], ["The Psychology of Money", "Morgan Housel", "Business", "images/book-25.webp", "money mind", 1], ["Rich Dad Poor Dad", "Robert T. Kiyosaki", "Business", "images/book-26.webp", "money business", 1]],cart={};
var $=function(i){return document.getElementById(i)},grid=$("grid"),cat="All";
var cats=["All"].concat(D.map(function(b){return b[2]}).filter(function(c,i,a){return a.indexOf(c)==i}));
cats.forEach(function(c){var b=document.createElement("button");b.className="tab";b.textContent=c;b.setAttribute("aria-pressed",c=="All");b.onclick=function(){cat=c;[].forEach.call($("tabs").children,function(x){x.setAttribute("aria-pressed",x==b)});filter()};$("tabs").appendChild(b)});
D.forEach(function(b,i){var c=document.createElement("div");c.className="card";c.style.setProperty("--d",i);
c.innerHTML='<div class="tilt"><span class="badge">\u20b9150</span><img loading="lazy"></div><h3></h3><span class="au"></span><span class="ct"></span><div class="acts"><button class="add">Add to order</button><a target="_blank" rel="noopener">Ask</a></div>';
var im=c.querySelector("img");im.src=b[3];im.loading="lazy";im.decoding="async";im.alt="Cover of "+b[0];c.querySelector("h3").textContent=b[0];c.querySelector(".au").textContent="by "+b[1];c.querySelector(".ct").textContent=b[2];
c.querySelector("a").href="https://wa.me/"+WA+"?text="+encodeURIComponent("Hello The Bibliophile Store, I would like to know more about \""+b[0]+"\" by "+b[1]+" (Rs. 150).");
var add=c.querySelector(".add");add.onclick=function(){if(cart[i]){delete cart[i];add.textContent="Add to order";add.classList.remove("on")}else{cart[i]=1;add.textContent="\u2713 Added";add.classList.add("on")}upd()};
var t=c.querySelector(".tilt");t.onpointermove=function(e){var r=t.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;t.style.setProperty("--ry",(x-.5)*18+"deg");t.style.setProperty("--rx",(.5-y)*18+"deg");t.style.setProperty("--sx",(150-x*200)+"%")};
t.onpointerleave=function(){t.style.setProperty("--rx","0deg");t.style.setProperty("--ry","0deg");t.style.setProperty("--sx","150%")};
c.dataset.s=(b[0]+" "+b[1]).toLowerCase();c.dataset.c=b[2];grid.appendChild(c)});
function filter(){var q=$("q").value.toLowerCase(),n=0;[].forEach.call(grid.children,function(c){var ok=(cat=="All"||c.dataset.c==cat)&&c.dataset.s.indexOf(q)>-1;c.classList.toggle("hide",!ok);if(ok)n++});$("empty").style.display=n?"none":"block"}
$("q").oninput=filter;
function upd(){var n=Object.keys(cart).length,k=$("cart");$("cn").textContent=n;$("ct").textContent="\u20b9"+n*150;k.classList.toggle("show",n>0);k.classList.remove("bump");void k.offsetWidth;k.classList.add("bump")}
$("send").onclick=function(){var l=Object.keys(cart).map(function(i,j){return (j+1)+". "+D[i][0]+" - "+D[i][1]}).join("\n");window.open("https://wa.me/"+WA+"?text="+encodeURIComponent("Hello The Bibliophile Store,\n\nI would like to order these books (Rs. 150 each):\n\n"+l+"\n\nTotal: Rs. "+Object.keys(cart).length*150+"\n\nPlease confirm availability and delivery to my address."),"_blank")};
document.getElementById("f").onsubmit=function(e){e.preventDefault();window.open("https://wa.me/"+WA+"?text="+encodeURIComponent("Hello! I am "+n.value+". I am looking for: "+t.value+". Preference: "+c.value+"."),"_blank")};
document.getElementById("sell").href="https://wa.me/"+WA+"?text="+encodeURIComponent("Hello! I have used books to sell. Here is my list:");
$("join").href="https://wa.me/"+WA+"?text="+encodeURIComponent("Hello! I am a passionate reader and would like to read books with The Bibliophile Store.");
var B=[["\ud83e\udde0","Keeps your mind sharp","Regular reading keeps your brain active and your focus strong."],["\ud83c\udf3f","Helps you unwind","A good book is a calm break from screens and noise."],["\ud83d\udcac","Builds vocabulary","You pick up new words and express yourself better."],["\u2764\ufe0f","Grows empathy","Stories let you live other lives and understand other people."],["\ud83d\udca1","Sparks ideas","Great books hand you new ways to think and decide."],["\ud83c\udf0d","Widens your world","Travel through history, science and cultures from your chair."]],bi=0,bt;
B.forEach(function(x,i){var d=document.createElement("i");d.onclick=function(){bi=i;bs()};$("dots").appendChild(d)});
function bs(){var x=B[bi];$("sl").innerHTML='<span class="ic">'+x[0]+'</span><h3>'+x[1]+'</h3><p>'+x[2]+'</p>';[].forEach.call($("dots").children,function(d,i){d.classList.toggle("on",i==bi)});var br=$("bar");br.style.transition="none";br.style.width="0";void br.offsetWidth;br.style.transition="width 5s linear";br.style.width="100%";clearTimeout(bt);bt=setTimeout(function(){bi=(bi+1)%B.length;bs()},5000)}
bs();
var h=document.querySelector(".hero");for(var i=0;i<14;i++){var f=document.createElement("span");f.className="fl";f.style.left=Math.random()*100+"%";f.style.animationDuration=(9+Math.random()*9)+"s";f.style.animationDelay=(-Math.random()*12)+"s";h.appendChild(f)}
for(i=0;i<9;i++){var u=document.createElement("span");u.className="bub";var s=20+Math.random()*50;u.style.cssText="width:"+s+"px;height:"+s+"px;left:"+Math.random()*100+"%;bottom:-60px;animation-duration:"+(7+Math.random()*7)+"s;animation-delay:"+(-Math.random()*9)+"s";$("bubs").appendChild(u)}
var rv=document.querySelectorAll(".head,.pillars div,.used .wrap>*,.two>*,.faq,.stats div,.perks div,.readers>*,.comm .wrap");
[].forEach.call(rv,function(e){e.classList.add("reveal")});
function cnt(e){var n=+e.dataset.n,p=e.dataset.p||"",t0=performance.now();(function s(t){var k=Math.min((t-t0)/1200,1);e.textContent=p+Math.round(n*(1-Math.pow(1-k,3)));if(k<1)requestAnimationFrame(s)})(t0)}
if("IntersectionObserver" in window){var io=new IntersectionObserver(function(es){es.forEach(function(x){if(x.isIntersecting){x.target.classList.add("in");var b=x.target.querySelector("[data-n]");if(b)cnt(b);io.unobserve(x.target)}})},{threshold:.15});[].forEach.call(rv,function(e){io.observe(e)})}else{[].forEach.call(rv,function(e){e.classList.add("in");var b=e.querySelector("[data-n]");if(b)b.textContent=(b.dataset.p||"")+b.dataset.n})}
addEventListener("scroll",function(){var d=document.documentElement;$("prog").style.width=(scrollY/(d.scrollHeight-innerHeight)*100)+"%"},{passive:true});
$("tt").onclick=function(){scrollTo({top:0,behavior:"smooth"})};
document.getElementById("y").textContent=new Date().getFullYear();

(function(){
var $=function(i){return document.getElementById(i)},cards=[].slice.call($("grid").children);
function el(h){var d=document.createElement("div");d.innerHTML=h;return d.firstChild}
cards.forEach(function(c,i){if(D[i][5]){var b=document.createElement("span");b.className="new";b.textContent="NEW";c.querySelector(".tilt").appendChild(b)}c.querySelector(".tilt").addEventListener("click",function(){openM(i)})});
function add(i){cards[i].querySelector(".add").click()}
function inCart(i){return !!cart[i]}
function sim(i){var t=D[i][4].split(" ");return D.map(function(b,j){return [j,j==i?-1:b[4].split(" ").filter(function(x){return t.indexOf(x)>-1}).length+(b[2]==D[i][2]?1:0)]}).sort(function(a,b){return b[1]-a[1]}).slice(0,3).map(function(x){return x[0]})}
var ov=el('<div class="ov" id="ov"><div class="md" role="dialog" aria-modal="true"><button class="x" aria-label="Close">\u00d7</button><img alt=""><div><span class="ct"></span><h3></h3><p class="au"></p><div class="pr">\u20b9150</div><div class="acts"><button class="add">Add to order</button><a target="_blank" rel="noopener">Ask on WhatsApp</a></div><h4>You may also like</h4><div class="sim"></div></div></div></div>');
document.body.appendChild(ov);
function close(){ov.classList.remove("on")}
ov.onclick=function(e){if(e.target==ov)close()};ov.querySelector(".x").onclick=close;
addEventListener("keydown",function(e){if(e.key=="Escape"){close();chat.classList.remove("on")}});
function openM(i){var b=D[i],m=ov.querySelector(".md");m.querySelector("img").src=b[3];m.querySelector("img").alt="Cover of "+b[0];
m.querySelector("h3").textContent=b[0];m.querySelector(".au").textContent="by "+b[1];m.querySelector(".ct").textContent=b[2];
var a=m.querySelector(".add");function sy(){a.textContent=inCart(i)?"\u2713 Added":"Add to order";a.classList.toggle("on",inCart(i))}sy();a.onclick=function(){add(i);sy()};
m.querySelector(".acts a").href="https://wa.me/"+WA+"?text="+encodeURIComponent("Hello The Bibliophile Store, I would like to know more about \""+b[0]+"\" by "+b[1]+" (Rs. 150).");
var s=m.querySelector(".sim");s.innerHTML="";sim(i).forEach(function(j){var im=document.createElement("img");im.src=D[j][3];im.loading="lazy";im.decoding="async";im.alt=D[j][0];im.title=D[j][0];im.onclick=function(){openM(j)};s.appendChild(im)});
ov.classList.add("on");m.scrollTop=0}
var sp=document.createElement("button");sp.className="tab";sp.textContent="\ud83c\udfb2 Surprise me";sp.onclick=function(){openM(Math.floor(Math.random()*D.length))};document.querySelector(".tools").appendChild(sp);
/* Book Buddy */
var chat=el('<div class="chat" id="chat"><div class="ch"><div>Book Buddy<small>Tell me your mood, get a book</small></div><button aria-label="Close chat">\u00d7</button></div><div class="msgs" id="msgs"></div><div class="chips" id="chips"></div><form class="cf" id="cf"><input id="ci" placeholder="e.g. I want to focus better" autocomplete="off"><button>Send</button></form></div>');
var bb=el('<button class="bb" id="bb">\ud83d\udcd6 Find my next book</button>');
document.body.appendChild(chat);document.body.appendChild(bb);
var msgs=$("msgs"),greeted=false;
function say(h,who){var m=document.createElement("div");m.className="m "+who;if(typeof h=="string")m.textContent=h;else m.appendChild(h);msgs.appendChild(m);msgs.scrollTop=msgs.scrollHeight;return m}
bb.onclick=function(){chat.classList.add("on");bb.style.display="none";if(!greeted){greeted=true;bot("Hi! I'm Book Buddy. Tell me what you feel like reading, or tap an option below.")}};
chat.querySelector(".ch button").onclick=function(){chat.classList.remove("on");bb.style.display=""};
function bot(t,cb){var m=say('x',"b");m.innerHTML='<span class="dotsy"><span></span><span></span><span></span></span>';setTimeout(function(){m.textContent=t;if(cb)cb(m);msgs.scrollTop=msgs.scrollHeight},650)}
var CH=[["\ud83d\udcaa Build better habits","habits focus"],["\ud83d\udcb0 Money & business","money business"],["\ud83c\udf0c Escape into a story","fiction"],["\ud83c\udf1f Real life stories","bio"],["\ud83e\udde0 Think sharper","mind"],["\ud83c\udf3f Calm & peace","calm"],["\u2764\ufe0f Romance","romance"],["\ud83c\udfdb History","history"]];
CH.forEach(function(c){var b=document.createElement("button");b.textContent=c[0];b.onclick=function(){ask(c[0],c[1])};$("chips").appendChild(b)});
var SYN={money:/money|financ|invest|rich|wealth|earn|save|paisa/,focus:/focus|product|distract|concentrat|disciplin|study|procrastinat/,habits:/habit|routine/,romance:/romanc|love|spicy|couple/,history:/histor|war|rome|ancient|past/,inspire:/inspir|motivat|dream|hope|purpose|success/,mind:/think|mind|psycholog|decision|brain|smart|ideas/,calm:/calm|peace|stress|anxi|alone|lonel|sad|relax|tired/,business:/business|startup|leader|entrepren|manage|team|job/,fiction:/fiction|novel|story|thriller|escape|fantasy|adventure|fun/,bio:/biograph|real|true|famous|life stor/,india:/india|kalam|gandhi|freedom/,growth:/grow|improv|self|better|confiden/};
function pick(txt,keys){var k=keys?keys.split(" "):Object.keys(SYN).filter(function(x){return SYN[x].test(txt.toLowerCase())}),t=txt.toLowerCase();
var sc=D.map(function(b,j){var s=0;k.forEach(function(x){if(b[4].indexOf(x)>-1)s+=2});if(t.length>3&&(b[0]+" "+b[1]).toLowerCase().indexOf(t)>-1)s+=5;return [j,s+Math.random()*.5]}).sort(function(a,b){return b[1]-a[1]});
return {hit:sc[0][1]>=1,list:sc.slice(0,3).map(function(x){return x[0]})}}
function ask(txt,keys){say(txt,"u");var r=pick(txt,keys);
bot(r.hit?"Here are 3 I think you'll enjoy. Each is \u20b9150:":"I couldn't match that exactly, but these are reader favourites:",function(m){r.list.forEach(function(j){var d=el('<div class="rec"><img alt=""><div><b></b><span></span></div><button>Add</button></div>');
d.querySelector("img").src=D[j][3];d.querySelector("img").loading="lazy";d.querySelector("img").decoding="async";d.querySelector("img").onclick=function(){openM(j)};d.querySelector("b").textContent=D[j][0];d.querySelector("span").textContent=D[j][1];
var bt=d.querySelector("button");function sy(){bt.textContent=inCart(j)?"\u2713":"Add";bt.classList.toggle("on",inCart(j))}sy();bt.onclick=function(){add(j);sy()};m.appendChild(d)})})}
$("cf").onsubmit=function(e){e.preventDefault();var v=$("ci").value.trim();if(!v)return;$("ci").value="";ask(v)};
})();

(function(){var nm=document.getElementById("nm"),m=document.getElementById("cmsg"),k=0;
[].forEach.call(nm.querySelectorAll("[data-t]"),function(e){e.textContent="";e.dataset.t.split("").forEach(function(c){var l=document.createElement("span");l.className="l";l.textContent=c;l.style.setProperty("--k",k++);e.appendChild(l)})});
var M=["Two readers. One dream. A hundred stories.","Every book you order is a world we love sharing.","Thank you for reading with us.","Keep turning pages. Keep growing."],i=0;
function go(){nm.classList.remove("go");m.classList.add("o");void nm.offsetWidth;nm.classList.add("go");setTimeout(function(){m.textContent=M[i++%M.length];m.classList.remove("o")},900)}
go();setInterval(go,5000)})()
