/* Book descriptions shown in the popup when a cover is clicked.
   Format: "images/book-NN.webp": ["Description", "Best for"]
   Edit the text freely; keep the image path exactly as it is in app.js. */
var DESC={
"images/book-01.webp":["A corporate thriller set inside a New York based international bank in India. Amit, a sharp young MBA, joins the bank and gets pulled into boardroom politics, rivalries and a mentor who plays power games. A quick, gripping read about ambition and what people will do to win.","Readers who enjoy office drama, banking stories and fast thrillers"],
"images/book-02.webp":["The closing part of Ravi Subramanian's banking trilogy. Love, politics, raw aggression and money laundering collide in a story that moves between glamorous offices and dangerous secrets. It reads like a movie, with short chapters and plenty of twists.","Thriller fans and anyone curious about the hidden side of money"],
"images/book-03.webp":["A classic guide to personal effectiveness built on seven habits, from taking charge of your own life to planning what matters first and listening before you speak. Covey shows how lasting success starts with character and principles, not quick tricks. A book many readers return to every few years.","Students, professionals and anyone who wants a clear framework for life and work"],
"images/book-04.webp":["A blunt, funny take on self-help that says you cannot care about everything, so choose carefully what is worth your energy. Manson argues that accepting limits, failure and discomfort is the surest way to a calmer, more honest life. Casual in tone, serious in message.","Readers tired of positive-thinking advice who want straight talk"],
"images/book-05.webp":["Simon Sinek explores why some teams trust each other and give their best, while others are full of fear and politics. He explains how good leaders protect their people first, creating a circle of safety that makes the whole group stronger. Packed with real stories from the military and business.","Managers, team leads, founders and future leaders"],
"images/book-06.webp":["The story of our species, from early humans to the modern age, told in one sweeping narrative. Harari looks at how shared beliefs such as money, religion and nations let millions of strangers cooperate, and asks where that power is taking us. Big ideas, easy to follow, hard to forget.","Curious readers, UPSC and history lovers, and anyone who enjoys big-picture thinking"],
"images/book-07.webp":["A historical novel about the great war between Rome and Carthage, led on the Carthaginian side by the brilliant general Hannibal. Two boys, one Carthaginian and one Roman, become unlikely friends, only to end up on opposite sides of the conflict. Rich in battle scenes and ancient-world detail.","Fans of Roman history, war stories and epic historical fiction"],
"images/book-08.webp":["A practical guide to thinking from first principles when you are building a startup. Paras Chopra shows how to break a problem down to its basics, question assumptions and make decisions with a clear head instead of copying what everyone else does. Written by an Indian founder who has built a global software company.","Aspiring founders, product builders and students who want sharper thinking"],
"images/book-09.webp":["A well-known book of the law of attraction, based on the teachings of Abraham as shared by Esther and Jerry Hicks. It explains how your thoughts and feelings shape your experience and offers simple processes to help you move towards what you want. Gentle, hopeful and meant to be practised, not just read.","Readers interested in mindset, positive thinking and personal growth"],
"images/book-10.webp":["Chess legend Garry Kasparov tells the story of his famous matches against the computer Deep Blue and what they taught him about machines and people. He argues that artificial intelligence is best seen as a partner to human creativity, not a replacement for it. Personal, thoughtful and surprisingly hopeful.","Readers curious about AI, chess, technology and the future of work"],
"images/book-11.webp":["Harari turns from the past to the present and asks what we should know to live well today. He looks at technology, jobs, politics, fake news, religion and meaning, and invites you to think clearly in a noisy world. Short, sharp chapters that you can read one at a time.","Readers who want to understand the world today, including competitive exam aspirants"],
"images/book-12.webp":["Nassim Taleb shows how often we mistake luck for skill, in business, money and everyday life. With sharp humour he explains why success stories can mislead us and how to respect uncertainty instead of ignoring it. A mind-changing read about risk, chance and humility.","Investors, business readers and anyone who likes questioning common wisdom"],
"images/book-13.webp":["In a future nation where teenagers are forced to fight in a televised contest to the death, Katniss steps forward to take her little sister's place. The story follows her struggle to survive, protect others and stay true to herself. Fast, emotional and hard to put down.","Young adults and anyone who loves dystopian adventure"],
"images/book-14.webp":["A reflective book about the difference between feeling lonely and choosing solitude. Renuka Gavrani shows how spending time alone can become a way to know yourself, heal and grow stronger instead of something to fear. Calm, simple and comforting.","Readers who feel overwhelmed by noise and want peace and self-understanding"],
"images/book-15.webp":["The life story of Dr A.P.J. Abdul Kalam, from a modest childhood in Rameswaram to leading India's space and missile programmes and becoming President. He writes with warmth about his teachers, his family and the scientists who shaped him. A deeply inspiring story of hard work and humility.","Students, young dreamers and anyone who wants real-life inspiration"],
"images/book-16.webp":["Barack Obama looks back on his path to the presidency and his first term in office. He writes about the campaign, the decisions made in the White House and the personal cost of public life, with honest reflection along the way. A detailed look at modern politics from the inside.","Readers of politics, leadership and contemporary history"],
"images/book-17.webp":["Gandhi's own account of his early life, his experiments with truth, and how he developed his ideas on honesty, non-violence and self-discipline. He openly shares his mistakes as well as his successes. A key book for understanding the man behind India's freedom movement.","Students of history, UPSC aspirants and readers who value self-reflection"],
"images/book-18.webp":["A young shepherd named Santiago sets out from Spain to Egypt after dreaming of treasure near the pyramids. On the way he meets teachers, faces setbacks and learns to listen to his heart. A simple, beautiful fable about following your dreams and finding your purpose.","Readers who want a short, uplifting story that stays with them"],
"images/book-19.webp":["A short, practical guide to breaking free from constant distractions such as scrolling, snacking and instant entertainment. Thibaut Meurisse explains how our brain's reward system pulls us away from meaningful work and gives simple steps to take back your focus. Easy to finish in one sitting.","Students and professionals who struggle with phone habits and procrastination"],
"images/book-20.webp":["Nobel Prize winner Daniel Kahneman explains the two systems that drive our thinking: one fast and instinctive, the other slow and careful. Through everyday examples he reveals why we make predictable mistakes in judgement and how to spot them. A landmark book on the human mind.","Readers interested in psychology, decision-making and behaviour"],
"images/book-21.webp":["James Clear shows how tiny daily changes add up to remarkable results over time. He explains how habits form and gives a simple method to build good ones and break bad ones. Clear, practical and full of examples you can start using today.","Anyone who wants to build routines, study better or improve step by step"],
"images/book-22.webp":["A collection of short chapters on the common thinking errors that quietly affect our choices, from overconfidence to following the crowd. Rolf Dobelli explains each one in plain language so you can spot it in yourself and decide better. Easy to read in small bites.","Readers who want sharper thinking without heavy theory"],
"images/book-23.webp":["Cal Newport argues that the ability to concentrate deeply without distraction is becoming rare and extremely valuable. He gives clear rules and routines for protecting your attention and producing your best work. A strong guide for the age of notifications.","Students, exam aspirants, writers and professionals who need serious focus"],
"images/book-24.webp":["A contemporary romance about a supermodel in a business-style engagement and the reclusive billionaire who is her fiance's closest friend. Loyalty and desire pull in opposite directions as old secrets surface. Intense, emotional and full of tension. This is a mature romance for adult readers.","Adult readers who enjoy steamy, high-stakes romance"],
"images/book-25.webp":["Morgan Housel explains that doing well with money depends more on behaviour than on intelligence. Through short stories about greed, fear, luck and patience, he shows how to think about saving, investing and enough. Simple, wise and easy to apply.","Beginners in money matters, students and first-time earners"],
"images/book-26.webp":["Robert Kiyosaki contrasts the money lessons of his two father figures: one who worked for a salary, and one who built businesses and assets. The book encourages readers to learn about money, think about assets and take charge of their financial future. Simple and motivating, and often a first step into personal finance.","Young readers and anyone starting their financial journey"]
};
